
hydra:
  job:
    chdir: true
    name: TestSweeps
  run:
    dir: ./outputs/${hydra:job.name}

my_config: my_value
learning_rate: none
batch_size: none
epochs: none
optimizer: none

include:
  static_data: true